### ISSUE TITLE
Having Error after solver.click_recaptcha_v2(iframe=recaptcha_iframe)

### ISSUE THREAD

**Issue by jasonchong3329** [thicccat688/selenium-recaptcha-solver#17]
Hello，
  
  Need your help , I having error after solver.click_recaptcha_v2(iframe=recaptcha_iframe) , as below  : 
  
    solver.click_recaptcha_v2(iframe=recaptcha_iframe)

  site-packages\selenium_recaptcha_solver\solver.py", line 81, in click_recaptcha_v2
    captcha_challenge = self._wait_for_element(

  site-packages\selenium_recaptcha_solver\solver.py", line 230, in _wait_for_element
    return WebDriverWait(self._driver, timeout).until(ec.visibility_of_element_located((by, locator)))

  site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
    
    **I noticed that it only work on if have popup press PLAY to listen popout (multi-step audio) , if is single step then will have issue** 
    
![image](https://github.com/thicccat688/selenium-recaptcha-solver/assets/20553843/3249b848-463f-4f62-b0ae-d1205f6a2183)

**Comment by thicccat688** [comment]
Hello, 

Usually, when there's a timeout exception, it's because either your internet was too slow or something went wrong in the solving process like Google blocking your IP. However, I see you commented it doesn't work if it's a single step, so can you elaborate on that and include some examples?

I appreciate you making this issue!

**Comment by jasonchong3329** [comment]
Hello,

Thank for the reply.

The issue only happen on single step , example code : 

>     recaptcha_iframe = driver.find_element(By.XPATH, '//iframe[@title="reCAPTCHA"]')
>     solver.click_recaptcha_v2(recaptcha_iframe)  // After resolve the recaptcha , the website will automatically redirect to another page , I can see the resolve recaptcha is successfully and the website is redirect completed.
so I'm thinking maybe because the website redirect too fast ?
>  //other code......

**Comment by thicccat688** [comment]
Hello,

I had some time today, so I implemented a fix for your case. 

If you have any more issues or suggestions let me know!

**Comment by jasonchong3329** [comment]
> Hello,
> 
> I had some time today, so I implemented a fix for your case.
> 
> If you have any more issues or suggestions let me know!

Hello


Sorry , I have update the plugin to 1.8.1 

The issue still there , do I need clear any cache?

Error message same : 

site-packages\selenium_recaptcha_solver\solver.py", line 81, in click_recaptcha_v2
captcha_challenge = self._wait_for_element(

site-packages\selenium_recaptcha_solver\solver.py", line 230, in _wait_for_element
return WebDriverWait(self._driver, timeout).until(ec.visibility_of_element_located((by, locator)))

site-packages\selenium\webdriver\support\wait.py", line 95, in until
raise TimeoutException(message, screen, stacktrace)

**Comment by thicccat688** [comment]
Hello,

Could you send me the website you're trying to automate (Or send me the script you're using if it doesn't have sensitive data like passwords or secrets)? I can understand what's going on better that way.

**Comment by thicccat688** [comment]
Sure, here you go: tomasperestrelo21@gmail.com

**Comment by jasonchong3329** [comment]
> Sure, here you go: [tomasperestrelo21@gmail.com](mailto:tomasperestrelo21@gmail.com)

Hello
I have send you an email , please check.
Thank you for your help.

**Comment by thicccat688** [comment]
Hello, 

I'll be checking the issue out soon. Thank you for your cooperation!

**Comment by tomasserravento** [comment]
Hey @thicccat688 , how are you? Happens the same to me. It says "Google has detected automated queries. Try again later" but if I click manually to the audio button I can download it.

The captcha Im trying to resolve opens automatically so instead of using click_recaptcha_v2 I directly use solve_recaptcha_v2_challenge because it is already opened with the pictures to choose:

<img width="345" alt="image" src="https://github.com/thicccat688/selenium-recaptcha-solver/assets/81922863/6d7bd69e-ba91-4b68-a6ef-a1c08d360258">

Thanks for the amazing work!

**Comment by jasonchong3329** [comment]
hello
we can by pass the error for solve the issue , let the process continue run.
    try : 
        solver.click_recaptcha_v2(recaptcha_iframe)
    except Exception : 
        pass
        
    ......
